# Generated by Django 4.1.5 on 2023-01-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='картинка'),
        ),
    ]
