# Generated by Django 4.1.5 on 2023-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_lon_place_lng_placeimage_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
