# Generated by Django 4.1.5 on 2023-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placeimage_options_alter_place_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='порядковый номер'),
        ),
    ]
