# Generated by Django 4.1.5 on 2023-01-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_placeimage_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together=set(),
        ),
    ]
