# Generated by Django 4.1.5 on 2023-01-28 19:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_placeimage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='длинное описание'),
        ),
    ]
